// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: relay_one

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void relay_toggle_cb(lv_event_t * e);
void relay_toggle_cb_2(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
